# Generated by Django 5.0.4 on 2024-10-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_user', models.CharField(max_length=20)),
                ('reg_mail', models.EmailField(max_length=20)),
                ('reg_pass', models.CharField(max_length=12)),
            ],
        ),
    ]
