# Generated by Django 5.0.4 on 2024-10-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_app', '0002_alter_register_data_reg_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_data',
            name='reg_type',
            field=models.CharField(default='client', max_length=10),
        ),
    ]
