# Generated by Django 5.0.4 on 2024-10-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_app', '0003_register_data_reg_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(max_length=50)),
                ('query_data', models.CharField(max_length=5000)),
                ('query_date', models.DateField()),
                ('query_status', models.CharField(max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_app.register_data')),
            ],
        ),
        migrations.CreateModel(
            name='response_queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_title', models.CharField(max_length=50)),
                ('query_date', models.DateField()),
                ('response_data', models.CharField(max_length=5000)),
                ('resonded_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_app.register_data')),
            ],
        ),
    ]
