# Generated by Django 5.0.4 on 2024-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_app', '0004_new_query_response_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('upcoming', 'Up-coming'), ('ongoing', 'On-going'), ('hold', 'Hold'), ('closed', 'Closed')], max_length=20)),
                ('task_date', models.DateField()),
            ],
        ),
    ]
